[package]
name = "api-products-rust"
version = "0.1.0"
authors = ["Mariano Di Modugno <marianodimodugno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
rocket_codegen = "0.4.10"