apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-example
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: service-api-products
      port:
        number: 8090
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /one/?(.*)
        pathType: Prefix
        backend:
          service:
            name: service-api-products
            port:
              number: 8090
      - path: /two(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: test-second
            port:
              number: 80