apiVersion: v1
kind: Service
metadata:
  name: service-api-products
  labels:
    app: service-api-products
    service: service-api-products
spec:
  ports:
  - port: 8090
    name: http
  selector:
    app: service-api-products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api-products
  labels:
    app: service-api-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-api-products
  template:
    metadata:
      labels:
        app: service-api-products
    spec:
      containers:
      - name: api-products
        image: dimo1992/research:api-product-03
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_NAME
          value: "catalog"
        - name: DB_USER
          value: "db_user_catalog"
        - name: DB_PASSWORD
          value: "db_user_pass_catalog"            
        - name: DB_HOST
          value: "service-db-mysql"
        - name: DB_PORT
          value: "3306"            
        ports:
        - containerPort: 8090