apiVersion: v1
kind: Service
metadata:
  name: api-products
spec:
  ports:
  - port: 8090
  selector:
    app: api-products
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-products
spec:
  selector:
    matchLabels:
      app: api-products
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-products
    spec:
      containers:
      - image: dimo1992/research:api-product-01
        name: api-products
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
          name: api-products